# Generated by Django 4.1.5 on 2023-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Africa", "AF"),
                    ("Antarctica", "AN"),
                    ("Asia", "AS"),
                    ("Europe", "EU"),
                    ("North america", "NA"),
                    ("Oceania", "OC"),
                    ("South america", "SA"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
