# Generated by Django 4.1.5 on 2023-01-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_region_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
