# Generated by Django 4.1.5 on 2023-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_region_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="post",
            name="country",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
