# Generated by Django 4.1.5 on 2023-01-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_region_options_post_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=200, null=True)),
                ("author", models.CharField(max_length=200, null=True)),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.comment",
            ),
        ),
    ]
