# Generated by Django 4.1.5 on 2023-01-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_comments_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="date",
            new_name="created_at",
        ),
    ]
